# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='floor',
        ),
    ]
