# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_location_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.TextField(default='')),
                ('minor', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='beacon',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Location'),
        ),
    ]
