# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160212_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='imageUrl',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
