# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160212_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speaker',
        ),
        migrations.AddField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Speaker'),
        ),
    ]
