# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160212_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='speaker2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker2', to='blog.Speaker'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker1', to='blog.Speaker'),
        ),
    ]
