# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160212_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speaker2',
        ),
    ]
