# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160212_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speaker',
        ),
    ]
