# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160212_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker1', to='blog.Speaker'),
        ),
    ]
