# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160212_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='floor',
        ),
    ]
