# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_session_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Location'),
        ),
    ]
